### Phase 1 Data Analytics Report 
 Group members:
1. Chau Ying Jia (A23CS0213)
2. Ng Yu Hin (A23CS0148)
3. Sabrina Heng Wei Qi (A23CS0265)



#### 1. Dataset Description

##### Cars2025 Dataset

This dataset contains the actual transactional records of all cars registered with the Road Transport Department (JPJ) since 2000, excluding any personal identifiable data. Under Malaysian law, all vehicles must be registered with JPJ and be assigned a registration plate number before they can be used on the road. 

While there has been cleaning and validation conducted prior to publication, no other amendment or aggregation has been performed. Each row in the dataset represents one registration transaction. This is the most granular form of the data.

Attributes of the Car2025 dataset:

In [5]:
import pandas as pd

carData = {'Description': ['Car registered date ', 'Type of vehicle', 'Car brand ', 'Car model name ', 'Fuel used by the car ', 'Colour of the car ','State where the car was registered ']} 

frame = pd.DataFrame(carData, columns = ['Description'],
                    index = ['date_reg ', 'type ', 'maker ', 'model ', 'fuel ', 'colour ', 'state '])
frame.index.name = 'Attributes'
frame

pd.set_option('colheader_justify', 'left')
frame.style.set_properties(**{'text-align': 'left'})

##### FuelConsumption Dataset

The "FuelComsumption Dataset" contains comprehensive information on various vehicles. It includes details such as make, model, vehicle class, engine size, cylinder count, transmission type, and fuel type of those vehicles. Additionally, the dataset provides ranges for fuel consumption and CO2 emissions, offering insights into the environmental impact of each vehicle. The dataset encompasses a wide range of vehicle types, from compact to mid-size, full size, and includes both conventional and high-performance models. With this information, we can study trends in vehicle characteristics, fuel efficiency, and emissions. This dataset serves as a valuable resource for understanding the automotive landscape and informing discussions on environmental sustainability and transportation policies.

In [8]:
import pandas as pd


fuelData = {'Description': ['Year of manufacture for vehicle', 'Vehicle brand', 'Specific model of vehicle', 'Vehicle class based on their size (e.g. compact, mid-size)', 'Volume of engine in litres', 'Number of engine cylinders','Type of transmission system (e.g. A4(manual) or M5(auto))','Type of fuel used (e.g. X, Z)','Amount of fuel consumed by vehicle','Amount of CO2 emitted by vehicle']} 

frame = pd.DataFrame(fuelData, columns = ['Description'],
                    index = ['MODELYEAR', 'MAKE', 'MODEL', 'VEHICLECLASS', 'ENGINECLASS', 'CYLINDERS', 'TRANSMISSION','FUELTYPE','FUELCONSUMPTION','COEMISSIONS'])
frame.index.name = 'Attributes'
frame

pd.set_option('colheader_justify', 'left')
frame.style.set_properties(**{'text-align': 'left'})

#### 2. Research Question

In this section,we will be answering the following questions by analyzing the data:
- How do fuel types and vehicle characteristics affect CO2 emissions,what is the distribution of car types and their average emissions in Malaysia (2025)?
- Which vehicle categories contribute the most to carbon output in Malaysia based on 2025 car registration data
- How do engine size and cylinder count relate to emissions?
- Which states register the most high-emission cars?
- What is the relationship between fuel consumption and emissions?

#### 3. Data Cleaning and Preparation

1. Import required libraries:

In [14]:
import pandas as pd
import re

2. Load both datasets

In [17]:
fuel_df = pd.read_csv('FuelConsumption.csv')     
cars_df = pd.read_csv('cars_2025.csv')

3. Preview the data info, description and the first five rows for fuelConsumption dataset

In [20]:
fuel_df.info()
fuel_df.describe()
fuel_df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1067 entries, 0 to 1066
Data columns (total 13 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   MODELYEAR                 1067 non-null   int64
 1   MAKE                      1067 non-null   object
 2   MODEL                     1067 non-null   object
 3   VEHICLECLASS              1067 non-null   object
 4   ENGINESIZE                1067 non-null   float64
 5   CYLINDERS                 1067 non-null   int64
 6   TRANSMISSION              1067 non-null   object
 7   FUELTYPE                  1067 non-null   object
 8   FUELCONSUMPTION_CITY      1067 non-null   float64
 9   FUELCONSUMPTION_HWY       1067 non-null   float64
 10  FUELCONSUMPTION_COMB      1067 non-null   float64
 11  FUELCONSUMPTION_COMB_MPG  1067 non-null   int64
 12  CO2EMISSIONS              1067 non-null   int64
dtypes: float64(4), int64(4), object(5)
memory usage: 108.5+ KB

,MODELYEAR,MAKE,MODEL,VEHICLECLASS,ENGINESIZE,CYLINDERS,TRANSMISSION,FUELTYPE,FUELCONSUMPTION_CITY,FUELCONSUMPTION_HWY,FUELCONSUMPTION_COMB,FUELCONSUMPTION_COMB_MPG,CO2EMISSIONS
0,2014,ACURA,ILX,COMPACT,2.0,4,AS5,Z,9.9,6.7,8.5,33,196
1,2014,ACURA,ILX,COMPACT,2.4,4,M6,Z,11.2,7.7,9.6,29,221
2,2014,ACURA,ILX HYBRID,COMPACT,1.5,4,AV7,Z,6.0,5.8,5.9,48,136
3,2014,ACURA,MDX 4WD,SUV - SMALL,3.5,6,AS6,Z,12.7,9.1,11.1,25,255
4,2014,ACURA,RDX AWD,SUV - SMALL,3.5,6,AS6,Z,12.1,8.7,10.6,27,244

4. Preview the data info, description and the first five rows for fuelConsumption dataset

In [23]:
cars_df.info()
cars_df.describe()
cars_df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 263578 entries, 0 to 263577
Data columns (total 7 columns):
 #   Column    Non-Null Count   Dtype
---  ------    --------------   -----
 0   date_reg  263578 non-null  object
 1   type      263578 non-null  object
 2   maker     263578 non-null  object
 3   model     263578 non-null  object
 4   colour    263578 non-null  object
 5   fuel      263578 non-null  object
 6   state     263578 non-null  object
dtypes: object(7)
memory usage: 14.1+ MB

  date_reg    type        maker  model      colour  fuel         state
0  2025-01-01     motokar    BYD       Seal   white     electric  Rakan Niaga
1  2025-01-01  window_van    Cam   Placer-X  yellow  greendiesel        Johor
2  2025-01-01         jip  Chery  Jaecoo J7   green       petrol  Rakan Niaga
3  2025-01-01         jip  Chery  Jaecoo J7  silver       petrol  Rakan Niaga
4  2025-01-01         jip  Chery      Tiggo    grey       petrol  Rakan Niaga

4. Check different columns name to standardize before merging

In [26]:
print("Cars2025 columns:", cars_df.columns.tolist())
print("FuelConsumption columns:", fuel_df.columns.tolist())

Cars2025 columns: ['date_reg', 'type', 'maker', 'model', 'colour', 'fuel', 'state']
FuelConsumption columns: ['MODELYEAR', 'MAKE', 'MODEL', 'VEHICLECLASS', 'ENGINESIZE', 'CYLINDERS', 'TRANSMISSION', 'FUELTYPE', 'FUELCONSUMPTION_CITY', 'FUELCONSUMPTION_HWY', 'FUELCONSUMPTION_COMB', 'FUELCONSUMPTION_COMB_MPG', 'CO2EMISSIONS']

5. Check again for their missing values

In [28]:
print(cars_df.isnull().sum())
print()
print(fuel_df.isnull().sum())

date_reg    0
type        0
maker       0
model       0
colour      0
fuel        0
state       0
dtype: int64

MODELYEAR                   0
MAKE                        0
MODEL                       0
VEHICLECLASS                0
ENGINESIZE                  0
CYLINDERS                   0
TRANSMISSION                0
FUELTYPE                    0
FUELCONSUMPTION_CITY        0
FUELCONSUMPTION_HWY         0
FUELCONSUMPTION_COMB        0
FUELCONSUMPTION_COMB_MPG    0
CO2EMISSIONS                0
dtype: int64

6. Remove duplicate rows

In [32]:
cars_df = cars_df.drop_duplicates()
fuel_df = fuel_df.drop_duplicates()

7. Standardizing

In [35]:
#Remove spaces, symbols and change string to lowercase
cars_df.columns = cars_df.columns.str.strip().str.lower().str.replace(' ', '_')
fuel_df.columns = fuel_df.columns.str.strip().str.lower().str.replace(' ', '_')

#rename the maker to make to standardize
cars_df.rename(columns={'maker': 'make'}, inplace=True)

#column values (e.g., maker, model, MAKE, MODEL) by converting to lowercase and stripping spaces 
cars_df['make'] = cars_df['make'].str.strip().str.upper()
cars_df['model'] = cars_df['model'].str.strip().str.upper()
cars_df['fuel'] = cars_df['fuel'].str.lower().str.strip()

fuel_df['make'] = fuel_df['make'].str.strip().str.upper()
fuel_df['model'] = fuel_df['model'].str.strip().str.upper()
fuel_df['fueltype'] = fuel_df['fueltype'].str.lower().str.strip()

8. Remove outliers

In [38]:
#Remove outliers from fuelConsumption data
fuel_cleaned = fuel_df[
    (fuel_df['fuelconsumption_comb'] < 30) &
    (fuel_df['co2emissions'] < 600)
]

print(f"Cleaned cars_2025 shape: {cars_df.shape}")
print(f"Cleaned fuel_consumption shape: {fuel_cleaned.shape}")

Cleaned cars_2025 shape: (48437, 7)
Cleaned fuel_consumption shape: (1067, 13)

9. Merged the two datasets

In [42]:
# Merge datasets on make and model to match registrations with emissions info
merged_data = pd.merge(cars_df,fuel_cleaned,
                        on=['make', 'model'],
                        how='inner'
)

# Show the shape of the merged dataset
print(f"Merged data shape: {merged_data.shape}")

#Easy way to check on their column
print("merged_data columns:")
print(merged_data.columns.tolist())

Merged data shape: (9212, 18)
merged_data columns:
['date_reg', 'type', 'make', 'model', 'colour', 'fuel', 'state', 'modelyear', 'vehicleclass', 'enginesize', 'cylinders', 'transmission', 'fueltype', 'fuelconsumption_city', 'fuelconsumption_hwy', 'fuelconsumption_comb', 'fuelconsumption_comb_mpg', 'co2emissions']

In [44]:
# Show the first 5 rows to see all columns combined
merged_data.info()
merged_data.describe()
merged_data.head()

import os

if os.path.exists("cleaned_data.csv"):
    os.remove("cleaned_data.csv")

    merged_data.to_csv('merged_data.csv', index=False)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9212 entries, 0 to 9211
Data columns (total 18 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   date_reg                  9212 non-null   object
 1   type                      9212 non-null   object
 2   make                      9212 non-null   object
 3   model                     9212 non-null   object
 4   colour                    9212 non-null   object
 5   fuel                      9212 non-null   object
 6   state                     9212 non-null   object
 7   modelyear                 9212 non-null   int64
 8   vehicleclass              9212 non-null   object
 9   enginesize                9212 non-null   float64
 10  cylinders                 9212 non-null   int64
 11  transmission              9212 non-null   object
 12  fueltype                  9212 non-null   object
 13  fuelconsumption_city      9212 non-null   float64
 14  fuelconsumption_hwy       9212 non-null   float64
 15  fuelconsumption_comb      9212 non-null   float64
 16  fuelconsumption_comb_mpg  9212 non-null   int64
 17  co2emissions              9212 non-null   int64
dtypes: float64(4), int64(4), object(10)
memory usage: 1.3+ MB

#### 4. Data Aggregation and Group Operations

1. Average CO2 Emissions by Fuel Type

In [40]:
merged_data['fueltype'] = merged_data['fueltype'].replace({
    'x': 'Petrol',
    'z': 'Diesel'
})


fuel_group = merged_data.groupby('fueltype').agg({
    'co2emissions': 'mean',
    'fuelconsumption_comb': 'mean',
    'model': 'count'
}).rename(columns={'model': 'vehicle_count'})

fuel_group = fuel_group.sort_values(by='co2emissions', ascending=False)
fuel_group

          co2emissions  fuelconsumption_comb  vehicle_count
fueltype
Diesel    261.929524    11.383365             1575
Petrol    184.072149     7.999162             7637

2. Average CO2 by Vehicle Class

In [42]:
if 'vehicleclass' in merged_data.columns:
    class_group = merged_data.groupby('vehicleclass').agg({
        'co2emissions': 'mean',
        'fuelconsumption_comb': 'mean',
        'model': 'count'
    }).rename(columns={'model': 'vehicle_count'})

class_group.sort_values(by='co2emissions', ascending=False)

                       co2emissions  fuelconsumption_comb  vehicle_count
vehicleclass
SUV - STANDARD         294.241779    12.788395              517
SUBCOMPACT             282.318182    12.268182               88
FULL-SIZE              251.000000    10.900000               21
MINIVAN                244.186047    10.608140               86
TWO-SEATER             234.000000    10.161667              300
MINICOMPACT            232.012658    10.087764              237
SUV - SMALL            211.414494     9.190813             3298
MID-SIZE               197.086854     8.561502              426
STATION WAGON - SMALL  174.500000     7.600000               22
COMPACT                167.140147     7.261323             4217

3. Top CO2 Emitters

In [45]:
top_emitters = merged_data.groupby(['make', 'model'])['co2emissions'].max().reset_index()
top_emitters = top_emitters.sort_values(by='co2emissions', ascending=False).head(10)

# Reset index starting from 1
top_emitters.reset_index(drop = True, inplace = True)
top_emitters.index += 1
top_emitters.index.name = 'No.'
top_emitters

    make          model            co2emissions
No.
1         BENTLEY        MULSANNE  437
2            AUDI              R8  409
3    ASTON MARTIN        VANQUISH  359
4         BENTLEY  CONTINENTAL GT  356
5        MASERATI     GRANTURISMO  347
6         PORSCHE         911 GT3  322
7         PORSCHE         CAYENNE  313
8            AUDI              Q7  304
9            FORD         MUSTANG  304
10          DODGE      CHALLENGER  301

4. Emission trends by mechanical specs.

In [48]:
merged_data.groupby('cylinders')['co2emissions'].mean()
merged_data.groupby('enginesize')['co2emissions'].mean()
merged_data

,date_reg,type,make,model,colour,fuel,state,modelyear,vehicleclass,enginesize,cylinders,transmission,fueltype,fuelconsumption_city,fuelconsumption_hwy,fuelconsumption_comb,fuelconsumption_comb_mpg,co2emissions
0,2025-01-01,motokar,PORSCHE,911 CARRERA,grey,petrol,Johor,2014,MINICOMPACT,3.4,6,AM7,Diesel,11.6,8.3,10.1,28,232
1,2025-01-01,motokar,PORSCHE,911 CARRERA,grey,petrol,Johor,2014,MINICOMPACT,3.4,6,M7,Diesel,12.5,8.6,10.7,26,246
2,2025-01-02,motokar,HONDA,CIVIC,white,petrol,Selangor,2014,COMPACT,1.8,4,AV,Petrol,7.9,6.0,7.0,40,161
3,2025-01-02,motokar,HONDA,CIVIC,white,petrol,Selangor,2014,COMPACT,1.8,4,AV7,Petrol,8.1,6.2,7.2,39,166
4,2025-01-02,motokar,HONDA,CIVIC,white,petrol,Selangor,2014,COMPACT,1.8,4,M5,Petrol,8.5,6.6,7.6,37,175
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9207,2025-04-30,jip,VOLVO,XC60,white,hybrid_petrol,Pulau Pinang,2014,SUV - SMALL,3.2,6,AS6,Petrol,13.0,8.9,11.2,25,258
9208,2025-04-30,jip,VOLVO,XC60,silver,hybrid_petrol,Rakan Niaga,2014,SUV - SMALL,3.2,6,AS6,Petrol,13.0,8.9,11.2,25,258
9209,2025-04-30,jip,VOLVO,XC60,black,hybrid_petrol,W.P. Kuala Lumpur,2014,SUV - SMALL,3.2,6,AS6,Petrol,13.0,8.9,11.2,25,258
9210,2025-04-30,jip,VOLVO,XC60,white,hybrid_petrol,Rakan Niaga,2014,SUV - SMALL,3.2,6,AS6,Petrol,13.0,8.9,11.2,25,258
9211,2025-04-30,jip,VOLVO,XC60,blue,hybrid_petrol,Rakan Niaga,2014,SUV - SMALL,3.2,6,AS6,Petrol,13.0,8.9,11.2,25,258

5. Most emisssions based on states

In [51]:
# Group by 'state' and aggregate
state_summary = merged_data.groupby('state').agg({
    'co2emissions': ['mean', 'max', 'count']
}).sort_values(('co2emissions', 'mean'), ascending=False)

# Reset index to turn 'state' into a regular column
state_summary = state_summary.reset_index()

# Add an incremented index starting from 1
state_summary.index += 1
state_summary.index.name = 'No.'

# Display the result
state_summary

    state              co2emissions
                       mean         max  count
No.
1    W.P. Kuala Lumpur  208.012796   437  1563
2                Perak  199.695312   313   128
3                Johor  199.213542   322   576
4             Selangor  197.992701   322   685
5         Pulau Pinang  197.304659   313   279
6          Rakan Niaga  195.616549   313  5088
7              Sarawak  193.130719   313   153
8      Negeri Sembilan  192.200000   313    75
9               Melaka  191.977011   313    87
10          Terengganu  186.218182   313    55
11               Kedah  185.548571   313   175
12            Kelantan  183.099099   313   111
13              Perlis  182.387755   267    49
14               Sabah  182.220930   313    86
15              Pahang  182.205882   313   102

6.  Relationship between fuel consumption and emissions

In [54]:
merged_data['fueltype'] = merged_data['fueltype'].replace({
    'x': 'Petrol',
    'z': 'Diesel'
})
merged_data['fuel_efficiency'] = merged_data['co2emissions'] / merged_data['fuelconsumption_comb']

merged_data.groupby('fueltype')['fuel_efficiency'].mean()

fueltype
Diesel    23.010015
Petrol    23.012040
Name: fuel_efficiency, dtype: float64